version: "3.1"

services:
  tiny-calorie:
    image: dnshra/tinycalorie:1.0
    container_name: tiny-calorie
    volumes: 
      - /path/to/storage:/app/data
    networks:
      - network
    ports: 
      - 8080:80
    restart: unless-stopped
networks:
    network: